config/routes.rb
NlujanDeborahcYtungDbgeorgeFinal::Application.routes.draw do
  resources :users
  resources :reviews
  resources :postings
  resources :urop_applications do
    resources :emails
  end

  resources :students, :controller => 'users', :type => 'Student'
  resources :supervisors, :controller => 'users', :type => 'Supervisor'
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "/student_applications" => "urop_applications#student_application_index", :as => "student_application_index"
  get "/supervisor_applications" => "urop_applications#supervisor_application_index", :as => "supervisor_application_index"
  get "/supervisor_applications/:posting_id" => "postings#show_application", :as => "supervisor_application_show"

  get "/:application/email" => "urop_applications#email", :as => "email" 

    get '/404' =>'errors#not_found'
    get '/500' =>'errors#not_found'

  root :to => "welcome#landing"

  

end

app/models/supervisor.rb
# User class representation
class Supervisor < User
	# User model associations
	has_many :reviews
	has_many :postings
	has_many :urop_applications, through: :postings


	# Retrieves the supervisor overall rating
	def self.get_rating(id)
		supervisor = Supervisor.find(id)
		return supervisor.reviews.average("overall_rating")
	end
end

app/helpers/supervisors_helper.rb
module SupervisorsHelper
end

app/views/supervisors/_form.html.erb
<%= form_for(@supervisor) do |f| %>
  <% if @supervisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supervisor.errors.count, "error") %> prohibited this supervisor from being saved:</h2>

      <ul>
      <% @supervisor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supervisors/edit.html.erb
<h1>Editing supervisor</h1>

<%= render 'form' %>

<%= link_to 'Show', @supervisor %> |
<%= link_to 'Back', supervisors_path %>

app/views/supervisors/index.html.erb
<h1>Listing supervisors</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @supervisors.each do |supervisor| %>
      <tr>
        <td><%= link_to 'Show', supervisor %></td>
        <td><%= link_to 'Edit', edit_supervisor_path(supervisor) %></td>
        <td><%= link_to 'Destroy', supervisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supervisor', new_supervisor_path %>

app/views/supervisors/new.html.erb
<h1>New supervisor</h1>

<%= render 'form' %>

<%= link_to 'Back', supervisors_path %>

app/views/supervisors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_supervisor_path(@supervisor) %> |
<%= link_to 'Back', supervisors_path %>