config/routes.rb
NlujanDeborahcYtungDbgeorgeFinal::Application.routes.draw do
  resources :users
  resources :reviews
  resources :postings
  resources :urop_applications do
    resources :emails
  end

  resources :students, :controller => 'users', :type => 'Student'
  resources :supervisors, :controller => 'users', :type => 'Supervisor'
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "/student_applications" => "urop_applications#student_application_index", :as => "student_application_index"
  get "/supervisor_applications" => "urop_applications#supervisor_application_index", :as => "supervisor_application_index"
  get "/supervisor_applications/:posting_id" => "postings#show_application", :as => "supervisor_application_show"

  get "/:application/email" => "urop_applications#email", :as => "email" 

    get '/404' =>'errors#not_found'
    get '/500' =>'errors#not_found'

  root :to => "welcome#landing"

  

end

app/models/posting.rb
# Posting class representation
class Posting < ActiveRecord::Base
	has_many :urop_applications, dependent: :destroy
	belongs_to :supervisor
	has_many :reviews

	
	# Posting attribute validations
	validates :title, :presence => true
	validates :description, :presence => true
	validates :skills, :presence => true
	validates :funding_type, :presence => true

	# Search method to allow searching on all postings page
	def self.search(search, category)
		if category == '1'
			return self.search_all(search)
		elsif category == '2'
			return self.search_title(search)
		elsif category == '3'
			return self.search_department(search)
		elsif category == '4'
			return self.search_description(search)
		elsif category == '5'
			return self.search_skills(search)
		elsif category == '6'
			return self.search_supervisor(search)
		elsif category =='7'
			return self.search_funding_type(search)
		# return all postings
		else
			scoped
		end
	end

	# Universal search method to allow searching on all postings page
  	def self.search_all(search)
  		 if search
  		 	postings = Array.new
    		Posting.where(['title LIKE ? OR description LIKE ? OR skills LIKE ? OR funding_type LIKE?', "%#{search}%", "%#{search}%", "%#{search}%","%#{search}%"]).each do |posting|
    			postings.push(posting)
    		end
    		self.search_supervisor(search).each do |posting|
    			if !postings.include? posting
    				postings.push(posting)
    			end 
    		end
    		self.search_department(search).each do |posting|
    			if !postings.include? posting
    				postings.push(posting)
    			end
    		end
    		return postings
  		else
    		scoped
    	end
  	end

	# Search by title
	def self.search_title(search)
		if search
			where('title LIKE ?', "%#{search}%")
		else
			scoped
		end
	end


	# Search by description
	def self.search_description(search)
		if search
			where('description LIKE ?', "%#{search}%")
		else
			scoped
		end
	end

	# Search by skills
	def self.search_skills(search)
		if search
			where('skills LIKE ?', "%#{search}%")
		else
			scoped
		end
	end

	# Search by supervisor
	def self.search_supervisor(search)
		if search
			postings = Array.new
			split_word = search.split(" ")
			if split_word[1].nil?
				split_word[0].delete(" ") unless split_word[0].nil?
				Supervisor.where("first_name like ? or last_name like ? ", "%#{split_word[0]}%", "%#{split_word[0]}%").each do |supervisor|
					supervisor.postings.each do |posting|
						postings.push(posting)
					end
				end
			else
				if !split_word[2].nil?
					return postings
				else
					Supervisor.where("first_name like? or last_name like ?", "%#{split_word[1]}%", "%#{split_word[1]}%").each do |supervisor|
						supervisor.postings.each do |posting|
							postings.push(posting)
						end
					end
				end
			end
			return postings
		else
			scoped
		end
	end

	# Search by department
	def self.search_department(search)
		if search
			postings = Array.new
			Supervisor.where("department like?", "%#{search}%").each do |supervisor|
				supervisor.postings.each do |posting|
					postings.push(posting)
				end
			end
			return postings
		else
			scoped
		end
	end

	# Search by department
	def self.search_funding_type(search)
		if search
			where('funding_type LIKE ?', "%#{search}%")
		else
			scoped
		end
	end
end

app/controllers/postings_controller.rb
# Postings Controller
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]
  before_action :can_create, only: [:new, :create]

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all.search(params[:search], params[:category])
    @review = Review.new
    @urop_application = UropApplication.new
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
    @posting = Posting.find(params[:id])
    @urop_application = UropApplication.new
  end

  def show_application
    @posting = Posting.find(params[:posting_id])
    @applications = @posting.urop_applications
    @email = Email.new
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)
    respond_to do |format|
      if @posting.save
        format.html { redirect_to postings_path, notice: 'Posting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @posting }
      else
        format.html { render action: 'new' }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :description, :skills, :funding_type, :supervisor_id)
    end

    # Only supervisors can view, update or delete postings they own
    def check_owner
      unless @posting.supervisor_id == current_user.id
          redirect_to postings_path, :notice => "You can't access this page"
      end
    end

    # Only supervisors can create postings
    def can_create
      unless current_user.type == 'Supervisor'
        redirect_to postings_path, :notice => "You can't make UROP postings"
      end
    end
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/postings/_allpostings.html.erb
<% if @postings.empty? %>
<center><h2 >No results</h2><center>
<% end %>

<% @postings.each_slice(3) do |slice| %>
<div class="row-fluid">
  <% slice.each do |posting| %>
  <div class="span4">
    <h4> <%= link_to posting.title, posting_path(posting.id) %></h4>
    <p>Sponsor: <%= posting.supervisor.first_name %> <%= posting.supervisor.last_name %></p>
    <p> Department: <%= posting.supervisor.department %></p>
    <p>Project description: <%= posting.description %></p>
    <p>Skills: <%= posting.skills %></p>
    <p>Funding type: <%= posting.funding_type %></p>

    <!-- Only give users the option to see delete button for postings that they created, validated by can_delete anyway-->
    <% if posting.supervisor_id == current_user.id %>
      <div class="dropdown" style="float:left">
      <button class="btn btn-sm setting dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown">Settings&nbsp<span class="caret"></span></button>
      <ul class="dropdown-menu setting" aria-labelledby="dLabel">
        <li><a href="#"><%= link_to('Edit', edit_posting_path(posting), :method => :get) %></a></li>
        <li><a href="#"><%=link_to( 'Remove', postings_path(:id=>posting.id), method: :delete, data: { confirm: 'Are you sure?' } )%></a></li>
      </ul>
    </div>
    <% if posting.urop_applications.empty? %>
      <p> No applications </p>
    <% else %>
      <%= link_to "Applications", supervisor_application_show_path(posting), class: "btn btn-sm btn-primary",:method=>:get, style: "float:left;" %>
      <br><br>
      <p> You have <%= posting.urop_applications.length %> application(s) for your posting </p>
    <% end %>
    <% end %>

    <% if current_user.type == 'Student' %>
    <!-- Checks if user already submitted an application. A student can only have one application for a posting -->
    <% if UropApplication.where(:posting_id=>posting.id,:student_id=>current_user.id).exists? %>
      <button class="btn btn-sm" disabled="disabled">
        Application Submitted
      </button>
    <% else %>
      <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#apply-modal<%=posting.id%>">
        Apply Now
      </button>
    <% end %>
    <%= render "urop_applications/form", :posting => posting %>
  <% end %>
  </div> <!-- span -->
  <% end %>
</div> <!-- row fluid -->
<% end %>

app/views/postings/_form.html.erb
<!-- Form partial for creating new postings-->
<div class="editform">
  <%= form_for(@posting) do |f| %>
    <% if @posting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

        <ul>
        <% @posting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <% f.hidden_field :open, :value => true %>
      <div class="formMargin">
        <div>
          <%= f.label :"Posting Title" %>
          <%= f.text_field :title %>
        </div>

        <div>
          <%= f.label :"Posting Description" %>
          <%= f.text_area :description %>
        </div>

        <div>
          <%= f.label :"Posting Skills" %>
          <%= f.text_field :skills %>
        </div>

        <div>
          <%= f.label :"Posting Funding Type" %>
          <%= f.text_field :funding_type %>
        </div>

        <div>
          <%= f.hidden_field :supervisor_id, value: current_user.id %>
        </div>
    </div>
    <div class="actions centerize">
      <%= f.submit "Submit New Posting"%>
    </div>
  <% end %>
</div>

app/views/postings/_posting_status.html.erb
<%= form_for(posting) do |f| %>
	<% if posting.open? %>
		<% f.hidden_field :open, :value => false %>
	<% else %>
		<% f.hidden_field :open, :value => true %>
	<% end %>
	<%= f.submit %>
<% end %>

app/views/postings/_showmessage.html.erb
<!-- Modal -->
<div class="modal fade" id="message-modal<%=application.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"style="height:400px;">
    <div class="modal-content" style="height:400px;">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="margin:20px;">&times;</button>
      <div class="modal-body">
        <%= application.message %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal -->

app/views/postings/edit.html.erb
<h1>Editing posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', urop_applications_path %>

app/views/postings/index.html.erb
<% if current_user.type == "Student" %>
<a href="#" data-toggle="modal" data-target="#review-modal" style="margin:20px; float:right;"><button class="btn btn-primary btn-lg">
          Write a Review
</button></a>
<% end %>
<%= render "reviews/form" %>
<%end%>
<center><h3>UROP postings</h3></center>

<!-- Search Bar -->
<%= form_tag postings_path, :method => 'get', :id => "postings_search" do %>

<div class="input-group">

	<%= text_field_tag :search, params[:search], class: "form-control", type: "text", style: "height:30px; width:200px;" %>
	<div class="input-group-btn">
		<%= submit_tag "Search By", :name => nil, class: "btn btn-default" %>
		<%= select_tag(:category, options_for_select([['All', '1'],['Title', '2'],['Department','3'],['Description','4'], ['Skills','5'], ['Sponsor','6'], ['Funding type','7']], '1'), type:"button", class:"btn btn-default dropdown-toggle", style:"width:100px;") %>
	</div><!--button group-->
</div><!--input group-->
<% end %>
<!--All postings-->
<div id="postings">
	<%= render 'allpostings' %>
</div>

app/views/postings/index.js.erb
$("#postings").html("<%= escape_javascript(render("allpostings")) %>");

app/views/postings/new.html.erb
<center><h2>Create a new posting</h2></center>

<%= render 'form' %>

<%= link_to 'Back', urop_applications_path %>

app/views/postings/show.html.erb
<center><h4><%= @posting.title %><br>
	Supervisor: <%=@posting.supervisor.first_name%>&nbsp<%=@posting.supervisor.last_name%></h4></center>
<div class="span4">
    <h4> <%= link_to @posting.title, posting_path(@posting.id) %></h4>
    <p> Average Rating: <%= Supervisor.get_rating(@posting.supervisor.id) %> </p>
    <p>Sponsor: <%= @posting.supervisor.first_name %> <%= @posting.supervisor.last_name %></p>
    <p>Project description: <%= @posting.description %></p>
    <p>Skills: <%= @posting.skills %></p>
    <p>Funding type: <%= @posting.funding_type %></p>
<% if current_user.type == "Student" %>
<% if UropApplication.exists?(@posting.id,current_user.id) %>
      <button class="btn btn-sm" disabled="disabled">
        Application Submitted
      </button>
    <% else %>
      <button class="btn btn-sm" data-toggle="modal" data-target="#apply-modal<%=@posting.id%>">
        Apply Now
      </button>
    <% end %>
    <%= render "urop_applications/form", :posting => @posting %>
<% end %>
</div>
<div class="span8">
<h4>UROP Reviews</h4>
<% @posting.supervisor.reviews.each do |review| %>
	<div class="row-fluid">
	Review #<%= @posting.supervisor.reviews.index(review) + 1 %><br>
	<% if review.anonymous %>
		<p>Author : Anonymous </p>
	<% else %>
		<p>Author: <%= review.student.first_name%>&nbsp<%= review.student.last_name %>
	<% end %>
	<p>Overall Rating: <%= review.overall_rating %></p>
	<p>Supervisor Role: <%= review.supervisor_rating %></p>
	<p>Time Commitment: <%= review.time_commitment %>&nbsphours per week</p>
	<p>What I worked on: <%= review.work_description %></p>
	<p>Other comments: <%= review.reflection %></p>
	</div>
<% end %>
</div>

app/views/postings/show_application.html.erb
<center><h3> Applications for <%=@posting.title%></h3></center>
<div class="span2"></div>
<div class="span10">
<table class="table">
<thead>
	<tr>
		<th>Student Name</th>
		<th>Graduation year </th>
		<th>Email Address </th>
		<th>Resume </th>
		<th>Message</th>
	</tr>
</thead>
<tbody>
<% @applications.each do |application| %>
	<tr>
		<td><%= link_to application.student.first_name+" "+application.student.last_name, student_path(application.student.id) %></td>
		<td><%= application.student.year %></td>
		<td><%= application.student.email%></td>
		<% if !application.student.resume.content_type.nil? %>
			<td><%= link_to 'Resume', application.student.resume.expiring_url %></td>
		<% else %>
			<td>No resume uploaded</td>
 		<% end %>
		<td class="btn btn-sm" data-toggle="modal" data-target="#message-modal<%=application.id%>">View message
		</td>
		<td class="btn btn-sm" data-toggle="modal" data-target="#reply-modal<%=application.id%>">
		Send an Email
		</td>
		<%= render "showmessage", :application => application %>
  		<%= render "email/form", :application => application %>
	</tr>
<% end %>
</tbody>
</table>
</div>