config/routes.rb
NlujanDeborahcYtungDbgeorgeFinal::Application.routes.draw do
  resources :users
  resources :reviews
  resources :postings
  resources :urop_applications do
    resources :emails
  end

  resources :students, :controller => 'users', :type => 'Student'
  resources :supervisors, :controller => 'users', :type => 'Supervisor'
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "/student_applications" => "urop_applications#student_application_index", :as => "student_application_index"
  get "/supervisor_applications" => "urop_applications#supervisor_application_index", :as => "supervisor_application_index"
  get "/supervisor_applications/:posting_id" => "postings#show_application", :as => "supervisor_application_show"

  get "/:application/email" => "urop_applications#email", :as => "email" 

    get '/404' =>'errors#not_found'
    get '/500' =>'errors#not_found'

  root :to => "welcome#landing"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>urop.io</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
</head>
<body>
<% if current_user %>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <a class="navbar-brand">
    <strong style="color:white;">
      <%= link_to "urop.io", postings_path %>
    </strong>
  </a>
  <div class="collapse navbar-collapse" style="padding-top:6px">
    <ul class="nav navbar-nav">
      <% if current_user.type == 'Supervisor' %>
        <li><%= link_to 'My Profile', supervisor_path(:id=>current_user.id), class: "nav-text" %></li>
        <li><%= link_to 'New Posting', new_posting_path, class: "nav-text"%></li>
        <li><%= link_to 'All Postings', postings_path %></li>
        <li><%= link_to 'My Postings', urop_applications_path, class: "nav-text" %></li>
        <li><%= link_to "My Reviews", reviews_path, class: "nav-text" %></li>
      <% elsif current_user.type == 'Student' %>
        <li><%= link_to 'My Profile', student_path(:id=>current_user.id), class: "nav-text" %></li>
        <li><%= link_to 'My Applications', urop_applications_path, class: "nav-text"%></li>
        <li><%= link_to 'All Postings', postings_path %></li>
        <li><%= link_to "View Reviews", reviews_path, class: "nav-text" %></li>
      <% end %>
    </ul>
    <p id="logout-text" class="pull-right">
    <strong><%= current_user.email %></strong>
    <%= link_to "Log out", logout_path %>
    </p>
  </div>
</nav>

<%else %>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <a class="navbar-brand" href="#">
    <strong style="color:white;">
      <%= link_to "urop.io", root_path %>
    </strong>
  </a>
  <div class="collapse navbar-collapse float_right" style="padding-top:6px">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Join as Student', new_student_path %></li>
      <li><%= link_to "Join as Supervisor", new_supervisor_path %></li>
    </ul>
  </div>
</nav>
<% end %>


  
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :class => "flash", :id => "flash_#{name}" %>
<% end %>

 <%= yield %>
</body>
</html>